CREATE EXTENSION IF NOT EXISTS vector;


CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "platform_id" bigint NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "docs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "doc_name" text NOT NULL,
  "doc_text" text NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "chunks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "doc_id" bigint NOT NULL,
  "text" text NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "embeddings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "chunk_id" bigint NOT NULL,
  "vector" vector(512) NOT NULL,
  "model_name" text NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);


-- Семантический поиск (самый важный!)
CREATE INDEX IF NOT EXISTS idx_embeddings_vector 
ON embeddings USING hnsw (vector vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Для быстрого доступа к чанкам документа
CREATE INDEX IF NOT EXISTS idx_chunks_doc_id ON chunks (doc_id);

-- Для фильтрации документов по пользователю
CREATE INDEX IF NOT EXISTS idx_docs_user_id ON docs (user_id);

-- Для связи embeddings → chunks
CREATE INDEX IF NOT EXISTS idx_embeddings_chunk_id ON embeddings (chunk_id);

-- Уникальный индекс для платформенных ID пользователей, чтобы избежать дубликатов
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_platform_id ON users (platform_id);


ALTER TABLE "docs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chunks" ADD FOREIGN KEY ("doc_id") REFERENCES "docs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "embeddings" ADD FOREIGN KEY ("chunk_id") REFERENCES "chunks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
